# Generated by Django 4.1.10 on 2023-08-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed_ips',
            field=models.JSONField(default=list),
        ),
    ]
