# Generated by Django 4.1.10 on 2023-09-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_image_alter_user_profiles_profile_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/default-blog.png', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='user_profiles',
            name='profile_images',
            field=models.ImageField(default='static/profile_image.jpg', upload_to='img'),
        ),
    ]
